import pytest
import schemathesis
from fastapi import FastAPI
from schemathesis.specs.openapi.schemas import BaseOpenAPISchema


@pytest.fixture()
def app_schema(client) -> BaseOpenAPISchema:
    """
    Get an OpenAPI schema instance for the app created by the `client` fixture.
    """
    app: FastAPI = client.app
    assert client.app is not None
    openapi = app.openapi()
    result = schemathesis.from_dict(openapi)
    return result


schema = schemathesis.from_pytest_fixture("app_schema")


@schema.parametrize()
def test_api(case):
    """Run tests automatically generated by schemathesis."""
    case.call_and_validate()
