site_name: FastAPI CRUD Router
repo_url: https://github.com/awtkns/fastapi-crudrouter
repo_name: awtkns/fastapi-crudrouter
edit_uri: ''

theme:
  name: material
  # custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/bolt.svg
  favicon: assets/bolt-grad.svg
  language: en

nav:
  - Overview: index.md
  - Schemas: schemas.md
  - Backends:
      - In Memory: backends/memory.md
      - SQLAlchemy: backends/sqlalchemy.md
      - Databases (async): backends/async.md
      - Ormar (async): backends/ormar.md
      - Tortoise (async): backends/tortoise.md
  - Routing: routing.md
  - Pagination: pagination.md
  - Dependencies: dependencies.md
  - Contributing: contributing.md
  - Releases: releases.md

google_analytics:
  - UA-186315536-1
  - auto

markdown_extensions:
  - extra
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/awtkns/fastapi-crudrouter
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/adam-watkins-yvr/
  - icon: fontawesome/solid/globe
    link: https://awtkns.com
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/adamcwatkins/

extra_css:
  - css/main.css
  - css/termynal.css
extra_javascript:
  - js/termynal.js
  - js/termy.js
